In [86]:
import numpy as np


### Arrays

In [87]:
a = np.array([1, 2, 3])

In [88]:
print(a[0])

1


In [89]:
b = np.ones((4,4, 4))
c = np.ones(4)
print((c))

[1. 1. 1. 1.]


In [90]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
e = np.random.random((2, 2))
print(e)

[[0.88995336 0.2116446 ]
 [0.46219059 0.36703418]]


In [92]:
from numpy import random

In [93]:
random.random((2, 2))

array([[0.00824209, 0.80206451],
       [0.31944689, 0.44352269]])

### Array Indexing

In [94]:
a[1]

2

In [95]:
a = np.array(([1,2,3,4], [5,6,7,8], [9,10,11,12]))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [96]:
a[1 : 3, 0 : 2] = 13
a

array([[ 1,  2,  3,  4],
       [13, 13,  7,  8],
       [13, 13, 11, 12]])

### Array Math

In [97]:
 x = np.array(([1,2], [3,4]), dtype=np.float64)
 y = np.array(([5,6], [7,8]), dtype=np.float64)

In [98]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [99]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [100]:
print(x * y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [101]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [102]:
v = np.array([9, 10])
w = np.array([11, 12])
print(np.dot(v,w))
print(x @ v)

219
[29. 67.]


### Broadcasting

In [103]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
v = np.array([1,0,1])

In [104]:
np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [105]:
x + v

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [106]:
x.shape

(4, 3)

In [107]:
v.shape

(3,)