In [80]:
import torch

In [81]:
print(torch.__version__)

2.0.1+cu118


In [82]:
x = torch.Tensor(2, 3, 4)
print(x)

tensor([[[-4.8858e+05,  3.2465e-41, -4.8862e+05,  3.2465e-41],
         [ 1.1210e-43,  0.0000e+00,  8.9683e-44,  0.0000e+00],
         [ 3.7377e+19,  3.2472e-41,  2.8183e+20,  6.1972e-04]],

        [[ 1.4588e-19,  7.2708e+31,  7.1430e+31,  1.5766e-19],
         [ 7.0295e+28,  1.6312e+19,  7.0976e+22,  1.8609e+34],
         [ 1.8315e+25,  7.5551e+31,  1.1351e-43,  0.0000e+00]]])


In [83]:
torch.ones(3)

tensor([1., 1., 1.])

In [84]:
torch.rand(2,3,4)

tensor([[[0.6360, 0.9955, 0.2652, 0.3781],
         [0.2771, 0.8837, 0.8492, 0.7201],
         [0.1947, 0.3193, 0.8854, 0.1633]],

        [[0.7783, 0.1114, 0.2053, 0.3115],
         [0.6983, 0.6896, 0.7660, 0.6726],
         [0.6826, 0.0692, 0.8742, 0.8470]]])

In [85]:
x.shape[0]

2

In [86]:
import numpy as np
a = np.array([[1,2], [3,4]])

In [87]:
print(type(x))
print(type(a))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


In [88]:
y = torch.from_numpy(a)
torch.sqrt(y)

tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])

In [89]:
torch.arange(6)

tensor([0, 1, 2, 3, 4, 5])

### Indexing

In [90]:
x[0][ : , 0]

tensor([-4.8858e+05,  1.1210e-43,  3.7377e+19])

### Dynamic Computation and Graph Backpropagation

In [91]:
x = torch.arange(3, dtype=torch.float32, requires_grad=True)

In [92]:
a = x + 2
b = a ** 2
c = b + 3
y = c.mean()
print("Y", y)

Y tensor(12.6667, grad_fn=<MeanBackward0>)


In [93]:
y.backward()

In [94]:
print(x.grad)

tensor([1.3333, 2.0000, 2.6667])


### Pre-trained Models for Image Classification

In [95]:
from PIL import Image
img = Image.open('dog.jpg')
img.show()

In [96]:
from torchvision import transforms
transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.485,0.456,0.406],
        std=[0.229,0.224,0.225]
    )
])

In [97]:
img_t = transform(img)

In [98]:
img_t.shape

torch.Size([3, 224, 224])

In [99]:
batch_t = torch.unsqueeze(img_t, 0)
batch_t.shape

torch.Size([1, 3, 224, 224])

In [100]:
from torchvision import models
alexnet = models.alexnet(pretrained=True)

/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [101]:
alexnet.eval()
with torch.no_grad():
  out = alexnet(batch_t)
print(out.shape)

torch.Size([1, 1000])


In [102]:
_, index = torch.max(out, 1) # Ignore first output, the actual max value, however what we want in the index of this max element

In [103]:
index

tensor([208])

In [104]:
out[0, :10]

tensor([-2.2716, -3.9061, -1.8370, -6.5818, -4.3262, -2.4756, -3.3697, -0.6961,
         3.7806, -0.3542])